In [ ]:
# Step 1: Import libraries
import pandas as pd   # For data handling
import numpy as np    # For numerical operations

In [14]:
import os
import pandas as pd

# Folder path
folder_path = "/content/drive/MyDrive/Colab Notebooks/"

# Find the CSV file that contains 'Metro' in its name
csv_files = [f for f in os.listdir(folder_path) if "Metro" in f and f.endswith(".csv")]

if len(csv_files) == 0:
    print("No CSV file with 'Metro' found in the folder.")
else:
    # Take the first matching file
    file_path = os.path.join(folder_path, csv_files[0])
    print("Loading file:", file_path)

    # Load the CSV
    df = pd.read_csv(file_path, low_memory=False)
    print("First 5 rows:")
    print(df.head())

Loading file: /content/drive/MyDrive/Colab Notebooks/Metro.csv
First 5 rows:
   Unnamed: 0            timestamp    TP2    TP3     H1  DV_pressure  \
0           0  2020-02-01 00:00:00 -0.012  9.358  9.340       -0.024
1          10  2020-02-01 00:00:10 -0.014  9.348  9.332       -0.022
2          20  2020-02-01 00:00:19 -0.012  9.338  9.322       -0.022
3          30  2020-02-01 00:00:29 -0.012  9.328  9.312       -0.022
4          40  2020-02-01 00:00:39 -0.012  9.318  9.302       -0.022

   Reservoirs  Oil_temperature  Motor_current  COMP  DV_eletric  Towers  MPG  \
0       9.358           53.600         0.0400   1.0         0.0     1.0  1.0
1       9.348           53.675         0.0400   1.0         0.0     1.0  1.0
2       9.338           53.600         0.0425   1.0         0.0     1.0  1.0
3       9.328           53.425         0.0400   1.0         0.0     1.0  1.0
4       9.318           53.475         0.0400   1.0         0.0     1.0  1.0

   LPS  Pressure_switch  Oil_level  Caudal_impulses
0  0.0              1.0        1.0              1.0
1  0.0              1.0        1.0              1.0
2  0.0              1.0        1.0              1.0
3  0.0              1.0        1.0              1.0
4  0.0              1.0        1.0              1.0

In [15]:
df.head()  # Preview first 5 rows

,Unnamed: 0,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Motor_current,COMP,DV_eletric,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses
0,0,2020-02-01 00:00:00,-0.012,9.358,9.340,-0.024,9.358,53.600,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
1,10,2020-02-01 00:00:10,-0.014,9.348,9.332,-0.022,9.348,53.675,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
2,20,2020-02-01 00:00:19,-0.012,9.338,9.322,-0.022,9.338,53.600,0.0425,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
3,30,2020-02-01 00:00:29,-0.012,9.328,9.312,-0.022,9.328,53.425,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
4,40,2020-02-01 00:00:39,-0.012,9.318,9.302,-0.022,9.318,53.475,0.0400,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0

In [16]:
df.info()            # Check data types, number of rows & columns
df.describe()        # Summary statistics of numeric columns
df.isnull().sum()    # Count of missing values per column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1516948 entries, 0 to 1516947
Data columns (total 17 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Unnamed: 0       1516948 non-null  int64
 1   timestamp        1516948 non-null  object
 2   TP2              1516948 non-null  float64
 3   TP3              1516948 non-null  float64
 4   H1               1516948 non-null  float64
 5   DV_pressure      1516948 non-null  float64
 6   Reservoirs       1516948 non-null  float64
 7   Oil_temperature  1516948 non-null  float64
 8   Motor_current    1516948 non-null  float64
 9   COMP             1516948 non-null  float64
 10  DV_eletric       1516948 non-null  float64
 11  Towers           1516948 non-null  float64
 12  MPG              1516948 non-null  float64
 13  LPS              1516948 non-null  float64
 14  Pressure_switch  1516948 non-null  float64
 15  Oil_level        1516948 non-null  float64
 16  Caudal_impulses  1516948 non-null  float64
dtypes: float64(15), int64(1), object(1)
memory usage: 196.7+ MB

Unnamed: 0         0
timestamp          0
TP2                0
TP3                0
H1                 0
DV_pressure        0
Reservoirs         0
Oil_temperature    0
Motor_current      0
COMP               0
DV_eletric         0
Towers             0
MPG                0
LPS                0
Pressure_switch    0
Oil_level          0
Caudal_impulses    0
dtype: int64

In [17]:
df.shape            # Number of rows & columns
df.columns          # List all column names

Index(['Unnamed: 0', 'timestamp', 'TP2', 'TP3', 'H1', 'DV_pressure',
       'Reservoirs', 'Oil_temperature', 'Motor_current', 'COMP', 'DV_eletric',
       'Towers', 'MPG', 'LPS', 'Pressure_switch', 'Oil_level',
       'Caudal_impulses'],
      dtype='object')

In [18]:
df = df.fillna(method='ffill')  # forward fill missing values

/tmp/ipython-input-3169101471.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')  # forward fill missing values

In [19]:
df = df.drop_duplicates()

In [21]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['TP2', 'TP3', 'DV_pressure']] = scaler.fit_transform(df[['TP2', 'TP3', 'DV_pressure']])

In [24]:
df.rename(columns={'DV_eletric':'DV_electric'}, inplace=True)

In [25]:
from sklearn.model_selection import train_test_split

# Select features and target
X = df[['TP2', 'TP3', 'DV_pressure', 'Motor_current']]  # Features
y = df['COMP']  # Target (example)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (1213558, 4)
Testing set: (303390, 4)